version: '3'
services:
  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      # - ./Envoy/https.crt:/etc/ssl/certs/https.crt
  flaskapi:
    build: PythonCode/
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317
    depends_on:
      - jaeger
      - collector

  collector:
    # image: otel/opentelemetry-collector-contrib:0.58.0
    # command: ["--config=/conf/collector-config.yaml"]
    # volumes:
    #   - ./collector-config.yaml:/conf/collector-config.yaml
    build: opentelemetry/
    ports:
    - 1888:1888 # pprof extension
    - 8888:8888 # Prometheus metrics exposed by the collector
    - 8889:8889 # Prometheus exporter metrics
    - 13133:13133 # health_check extension
    - 4317:4317 # OTLP gRPC receiver
    - 4318:4318 # OTLP http receiver
    - 55679:55679 # zpages extension
    depends_on:
      - zipkin-all-in-one
      - prometheus
      - jaeger

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
      - "16686:16686"
      - "14268:14268"

    environment:
      # - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
