version: '3'
services:
  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      # - ./Envoy/https.crt:/etc/ssl/certs/https.crt
  flaskapi:
    build: PythonCode/
    ports:
      - "5000:5000"
  prometheus:
    build: prometheus/
    ports:
      - "9090:9090"
  opentelemetry:
    build: opentelemetry/
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55678"       # OpenCensus receiver
      - "55680:55679" # zpages extension

  # opentelemetry:
  #   build: opentelemetry/
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -sf http://localhost:13133 || exit 1"]
  #     interval: 1s
  #     timeout: 120s
  #     retries: 120
  #     start_period: 5s
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   ports:
  #   - "55679:55679"